config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'errors/not_found'
  get 'errors/internal_server_error'
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions', omniauth_callbacks: 'users/omniauth_callbacks' }

  HomeController.action_methods.each do |action|
    get action.to_sym, to: "home##{action}"
  end
  resources :articles, only: [:show]

  resources :divisions, only: [:index] do
    resources :degrees, only: [:show]
  end

  resources :contacts, only: %i[new create]
  resources :setup, only: %i[show update]
  resources :cards, only: [:new, :create, :destroy]
  resources :reservations, only: %i[index destroy]
  resources :charges, only: [:index]
  resources :transfers, only: [:index]
  resources :availabilities, only: %i[index show destroy update]
  resources :enrollments, only: %i[index update] do
    resources :evaluations, only: %i[new create]
  end
  resources :courses, except: [:edit, :update]
  resources :slots, only: [:index]
  resources :emails, only: [:create]
  resources :users, only: %i[show update] do
    resources :appointments, only: [:new, :create, :destroy]
    member do
      get :finish_signup
      patch :complete_signup
      get :student_welcome
      get :professor_welcome
      get :interview
      get :reject
      get :approve
    end
  end

  resources :petitions, only: %i[create show]
  resources :instances, only: [:show, :update] do
    member { get :confirmed }
    resources :posts, only: [:create]
    resources :meetings, only: %i[show edit update]
    resources :assignments, except: [:index] do
      resources :submissions, only: %i[new create update]
    end
  end
  resources :dashboard, only: [:index] do
    collection { get :activities }
  end

  resources :conversations, only: [:index, :show] do
    member do
      post :reply
    end
  end

  resources :messages, only: %i[new create]
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  authenticated :user do
    root 'dashboard#index', as: :authenticated_root
  end

  root to: 'home#index'
  mount StripeEvent::Engine, at: '/stripe-events'
  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
  get 'sitemap.xml' => 'home#sitemap', format: :xml
  get 'robots.txt' => 'home#robots', format: :text
end

app/controllers/conversations_controller.rb
# frozen_string_literal: true

class ConversationsController < ApplicationController
  before_action :authenticate_user!
  before_action :check_for_card
  before_action :set_mailbox
  before_action :set_conversation, except: [:index]
  add_breadcrumb 'Dashboard', :authenticated_root_path

  def index
    add_breadcrumb 'Conversations', :conversations_path
    @conversations = @mailbox.conversations.page(params[:page]).per(10)
  end

  def show
    add_breadcrumb 'Conversations', :conversations_path
    add_breadcrumb("Conversation with #{@conversation.participants.find do |s|
      s.id != current_user.id
    end.try(:name)}", conversation_path(@conversation))
  end

  def reply
    current_user.reply_to_conversation(@conversation, params[:body])
    flash[:success] = 'Reply sent'
    redirect_to conversation_path(@conversation)
  end

  private

  def set_conversation
    @conversation ||= @mailbox.conversations.find(params[:id])
  end

  def set_mailbox
    @mailbox ||= current_user.mailbox
  end
end

app/views/conversations/_conversation.html.haml
.media
  - user = conversation.participants.find {|s| s.id != current_user.id }
  = render 'users/avatar', user: user
  .media-body
    %h5.media-heading= user.name
    .pull-right
      %h6.text-muted= conversation.last_message.created_at.strftime("%b %-d, %H:%M %p")
    %p= link_to conversation.subject, conversation_path(conversation)

app/views/conversations/_participants.html.haml
- conversation.participants.each do |participant|
  - unless participant == current_user
    = image_tag current_user.photo.present? ? current_user.photo.url(:thumb) : 'defaults/photos_default.jpg', class: "img-circle img-responsive img-no-padding"

app/views/conversations/index.html.haml
.container.dashboard
  .row.m-t-50
    = render 'layouts/sidebar'
    .col-md-9.col-sm-9.col-xs-12
      = render 'layouts/breadcrumbs'
      %p= link_to 'Start conversation', new_message_path, class: 'btn btn-lg btn-primary'

      = render partial: 'conversations/conversation', collection: @conversations
      = paginate(@conversations)

app/views/conversations/show.html.haml
.container.dashboard
  .row.m-t-50
    = render 'layouts/sidebar'
    .col-md-9.col-sm-9.col-xs-12
      = render 'layouts/breadcrumbs'
      .row
        .col-xs-12
          - @conversation.mark_as_read(current_user)
          .panel.panel-default
            .panel-heading= @conversation.subject
            .panel-body
              .messages
                - @conversation.receipts_for(current_user).each do |receipt|
                  = render 'messages/message', message: receipt.message
              .media.media-post
                = form_tag reply_conversation_path(@conversation), method: :post do
                  = render 'users/avatar', user: current_user
                  .media-body
                    = text_area_tag 'body', nil, rows: 6, class: 'form-control border-input', placeholder: 'Type something...', required: true
                    .media-footer
                      = submit_tag "Send", class: 'btn btn-infp btn-fill btn-wd pull-right'