config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'errors/not_found'
  get 'errors/internal_server_error'
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions', omniauth_callbacks: 'users/omniauth_callbacks' }

  HomeController.action_methods.each do |action|
    get action.to_sym, to: "home##{action}"
  end
  resources :articles, only: [:show]

  resources :divisions, only: [:index] do
    resources :degrees, only: [:show]
  end

  resources :contacts, only: %i[new create]
  resources :setup, only: %i[show update]
  resources :cards, only: [:new, :create, :destroy]
  resources :reservations, only: %i[index destroy]
  resources :charges, only: [:index]
  resources :transfers, only: [:index]
  resources :availabilities, only: %i[index show destroy update]
  resources :enrollments, only: %i[index update] do
    resources :evaluations, only: %i[new create]
  end
  resources :courses, except: [:edit, :update]
  resources :slots, only: [:index]
  resources :emails, only: [:create]
  resources :users, only: %i[show update] do
    resources :appointments, only: [:new, :create, :destroy]
    member do
      get :finish_signup
      patch :complete_signup
      get :student_welcome
      get :professor_welcome
      get :interview
      get :reject
      get :approve
    end
  end

  resources :petitions, only: %i[create show]
  resources :instances, only: [:show, :update] do
    member { get :confirmed }
    resources :posts, only: [:create]
    resources :meetings, only: %i[show edit update]
    resources :assignments, except: [:index] do
      resources :submissions, only: %i[new create update]
    end
  end
  resources :dashboard, only: [:index] do
    collection { get :activities }
  end

  resources :conversations, only: [:index, :show] do
    member do
      post :reply
    end
  end

  resources :messages, only: %i[new create]
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  authenticated :user do
    root 'dashboard#index', as: :authenticated_root
  end

  root to: 'home#index'
  mount StripeEvent::Engine, at: '/stripe-events'
  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
  get 'sitemap.xml' => 'home#sitemap', format: :xml
  get 'robots.txt' => 'home#robots', format: :text
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index
    @email = Email.new
  end

  def about; end

  def privacy; end

  def terms; end

  def professor_terms; end

  def faq
    @faqs = Faq.all
  end

  def tuition; end

  def academics; end

  def thanks; end

  def blog
    @articles = Article.all.order('created_at desc').page(params[:page]).per(5)
  end

  def cookies_policy; end

  def error
    fail('halp!')
  end

  def sitemap
    path = Rails.root.join('public', 'sitemaps', 'sitemap.xml')
    if File.exist?(path)
      render xml: open(path).read
    else
      render text: 'Sitemap not found.', status: :not_found
    end
  end

  def robots; end
end

app/views/home/about.html.haml
.container
  .row.m-t-100
    .col-md-6.col-md-offset-3
      .info
        .description
          %h2.light-weight The Brasden Difference
          %br
          %p We have completely reimagined the degree earning process to give you the best education at the least cost.
  .row.m-t-100
    .col-md-12
      %small MISSION
      %h2.light-weight The Brasden College is the world's college
      .row.m-t-40
        .col-md-6
          %p The nature of learning is changing and we are at the forefront of this seismic shift. Every year, tens of millions of people enter college. Who will they study with? What tools will they use to learn more effectively? We are building the largest network of exceptional teachers, professors, and students to create the next online educational platform to move people from information-based learning to a fully well-rounded education; all of which, leads to a Bachelor of Arts or a Bachelor of Science degree.
          %p Knowledge is an essential requirement to become a productive and fullfilling member of global society. Since the rise of information technology there is more information available at the click of a mouse. No longer locked in libraries, this knowledge is freely available to anyone with an internet connection. At the same time, information is not knowledge, nor is it particular useful without context. For this reason, a guided liberal arts education is even more important today than it ever was.
        .col-md-6
          %p At Brasden, we believe that the best learning happens with the guide of professional teachers. The glut of information available today makes contextualizing that information, processing that knowledge and guiding a student to a fullfilling life experience even more precient than a couple decades ago.
          %p At The Brasden College, we believe that higher eduation should not be prohibitively expensive. Earning a college degree should not require debt. We believe that professors should earn a living wage and not struggle to make ends meet shuffling from one institution to another. Accordingly, we offer degree-leading courses cheaper than any other college or university in the developed world. We compensate professors with livable earnings from those fees. Interested in becoming a part of the experinece? Come join us. We're just getting started.
  .row.m-t-100
    .col-md-12
      %small LEARNING
      %h3.light-weight Person-to-person learning without room and board
    .row
      .col-md-4
        .info.info-horizontal
          .icon
            %i.ti-harddrives
          .description
            %h4 Learn on the web, iOS or Android
            %p Attend courses via the web, or on your mobile device from anywhere in the world.
            %a.btn.btn-simple.btn-info{href: new_user_registration_path} Get Started
      .col-md-4
        .info.info-horizontal
          .icon
            %i.ti-hand-open
          .description
            %h4 Small Class Sizes
            %p Our classes are capped at 25, with an average of 15 students in a single course.
            %a.btn.btn-simple.btn-info{href: new_user_registration_path} Get Started
      .col-md-4
        .info.info-horizontal
          .icon
            %i.ti-world
          .description
            %h4 Affordable courses leading to a degree
            %p No governemnt loan required. Our courses are only €175 for each student enrolled.
            %a.btn.btn-simple.btn-info{href: new_user_registration_path} Get Started
    .row
      .col-md-4
        .info.info-horizontal
          .icon
            %i.ti-direction-alt
          .description
            %h4 Wide variety of programes and degrees
            %p Chose a degree program in anything from Anthropology to Statistics.
            %a.btn.btn-simple.btn-info{href: new_user_registration_path} Get Started
      .col-md-4
        .info.info-horizontal
          .icon
            %i.ti-time
          .description
            %h4 Short 10 week long course durations
            %p Complete your degree in record time, without the red tape.
            %a.btn.btn-simple.btn-info{href: new_user_registration_path} Get Started
      .col-md-4
        .info.info-horizontal
          .icon
            %i.ti-bookmark-alt
          .description
            %h4 Earn an internationally recognized degree
            %p Your Swiss credential will give you a passport to countless opportunities.
            %a.btn.btn-simple.btn-info{href: new_user_registration_path} Get Started
.section.section-light-brown
  .container
    .row
      .col-md-12.text-center
        %h4 Interested in earning your degree?
        %br/
        %a.btn.btn-danger.btn-lg.btn-fill{:href => new_user_registration_path } Apply Now
.container
  .row.m-t-100
    .col-md-12
      %small TEACHING
      %h3.light-weight Small, motivated classes without the department politics
    .row
      .col-md-4
        .info.info-horizontal
          .icon
            %i.ti-blackboard
          .description
            %h4 Skip the commute
            %p No running between home and work or between campus to campus to teach.
            %a.btn.btn-simple.btn-info{href: new_user_registration_path(professor: true)} Get Started
      .col-md-4
        .info.info-horizontal
          .icon
            %i.ti-world
          .description
            %h4 Teach while you reseach and travel the world
            %p Maintain you research activities while attending courses from your laptop or mobile.
            %a.btn.btn-simple.btn-info{href: new_user_registration_path(professor: true)} Get Started
      .col-md-4
        .info.info-horizontal
          .icon
            %i.ti-pie-chart
          .description
            %h4 Course and enrollment tracking
            %p Track and monitor grades, assignments and enrollments like any other LMS.
            %a.btn.btn-simple.btn-info{href: new_user_registration_path(professor: true)} Get Started
    .row
      .col-md-4
        .info.info-horizontal
          .icon
            %i.ti-world
          .description
            %h4 Get paid weekly
            %p Your time is valuable. You shouldn't have to wait to earn that.
            %a.btn.btn-simple.btn-info{href: new_user_registration_path(professor: true)} Get Started
      .col-md-4
        .info.info-horizontal
          .icon
            %i.ti-write
          .description
            %h4 Develop new curriculum
            %p Want to teach a new course? Propose it, and we'll add it to the department offerings.
            %a.btn.btn-simple.btn-info{href: new_user_registration_path(professor: true)} Get Started
      .col-md-4
        .info.info-horizontal
          .icon
            %i.ti-stats-up
          .description
            %h4 Take control of your career
            %p Develop your academic potential while teaching students from across the globe.
            %a.btn.btn-simple.btn-info{href: "#"} Get Started
.section.section-light-brown
  .container
    .row
      .col-md-12.text-center
        %h4 Interested in teaching?
        %br/
        %a.btn.btn-danger.btn-lg.btn-fill{:href => new_user_registration_path(professor: true) } Apply Now

app/views/home/academics.html.haml
.container
  .row.m-t-100.m-b-50
    .col-md-6.col-md-offset-3
      .info
        .description
          %h2.light-weight Academics
          %br
          %p Requirements for the Bachelor of Arts or Bachelor of Science degree
  .row.m-t-100.m-b-50
    .col-md-8.col-md-offset-2
      %p The Brasden Institude offers courses of study leading to the degree of Bachelor of Arts and Bachelor of Science. The course requirements prescribe both the number of courses to be completed and the minimum grade level to be achieved; the curriculum also requires that each student explore several fields of knowledge and concentrate in one. The full requirements for the degree include meeting the minimum academic standards stated below, fulfilling the distribution requirement, and completing a major.
      %p The academic year is divided into 10 week periods. A student can take up to four courses in each period.
      %h4 Academic Requirement

      %p To be eligible for the Bachelor of Arts degree or Bachelor of Science degree a student must pass 32 courses including 19 with grades of C- or better) and complete all requirements for the major including an average of C minus or higher. A student may not repeat a course for which degree credit has been awarded.

      %h4 Distribution Requirement

      %h5 DIVISIONAL REQUIREMENT
      %p Designed to ensure that in their course of study at the Institude, students take an appropriately diverse distribution of courses across the full range of the curriculum.

      %p For the purposes of the requirement, courses are grouped into three divisions: Division I, Languages and the Arts; Division II, Social Studies; and Division III, Science and Mathematics. A full listing of the subjects in each division appears below.

      %p Students must complete at least three graded courses in each division. Two in each division must be completed before the student can take over 16 courses. The courses must be taken at the Insitude.

      %p Courses that fulfill the distribution requirement in Division I are designed to help students become better able to respond to the arts sensitively and intelligently by learning the language, whether verbal, visual, or musical, of a significant field of artistic expression. Students learn how to develop the capacity for critical discussion, to increase awareness of the esthetic and moral issues raised by works of art, and to grow in self-awareness and creativity.

      %p Courses which fulfill the Division II requirement consider the institutions and social structures that human beings have created, whether knowingly or unknowingly, and which in turn markedly affect their lives. These courses are intended to help the students recognize, analyze, and evaluate these human structures in order that they may better understand themselves and the social world in which they live.

      %p Courses which fulfill the Division III requirement are intended to provide some of the factual and methodological knowledge needed to be an informed citizen in a world deeply influenced by scientific thought and technological accomplishment, and to cultivate skill in exact and quantitative reasoning.

      %p Courses with the following designations receive divisional distribution credit as indicated:
      %br
      %p
        - Division.all.each_with_index do |division, index|
          %h5= "DIVISION #{"I" * (index + 1)}. #{division.name}"
          - division.degrees.each do |d|
            = d.name
            %br
          %br

      %h4 MAJOR REQUIREMENT

      %p The Major Requirement is designed to assure that all College undergraduates will have the experience of disciplined and cumulative study, carried on over an extended period of time, in some important field of intellectual inquiry. Students are required to declare a major and the selection is normally made at the time of application into the College.

      %p Majors are offered in the following fields:

      %p
        - Degree.all.each do |degree|
          = degree.name
          %br
      %h4 GENERAL STRUCTURE OF MAJORS

      %p 1) A student ordinarily must complete at least nine courses in his or her major field.

      %p 2) A prescribed sequence of courses, supplemented by parallel courses, and including a major seminar, is required in some major fields.

      %p Courses in many major programs require prerequisite courses in related areas. A full description of the detailed structure of each major is found under the heading of that major.

app/views/home/blog.html.haml
.container.blog
  .row
    .col-md-6.col-md-offset-3.text-center.title
      %h2 News and Updates
  - @articles.each do |article|
    .article
      .row
        .col-md-10.col-md-offset-1
          .text-center
            %a{:href => "#"}
              %h3.title= article.name
            %h6.title-uppercase= article.created_at.to_s(:long)
      .row
        .col-md-8.col-md-offset-2
          - if article.attachment.present?
            .article-image.text-center
              %a{:href => "#"}
                .card-big-shadow
                  .card{"data-radius" => "none", :style => "background-image: url(#{article.attachment.url(:large)});"}
          .article-content
            %p= truncate(article.body, length: 200, escape: false).html_safe
          .article-content.text-center.m-b-50
            = link_to 'Read more', article_path(article), class: 'btn btn-danger btn-fill btn-sm'

app/views/home/cookies_policy.html.haml
.container
  .row
    .col-lg-12
      %h2 Cookies
      .card.information-card
        .content
          %p.description Cookies are small text files which are downloaded to your computer, tablet or mobile phone when you visit a website or application. The website or application may retrieve these cookies from your web browser (eg Internet Explorer, Mozilla Firefox or Google Chrome) each time you visit, so they can recognise you, remember your preferences and provide you with a more secure online experience.

          %p.description Generally, cookies are very useful and are a common method used by almost every website you visit because they help to make your online experience as smooth as possible. For security reasons, many websites will not function at all without the use of cookies (or other similar technologies, such as "web beacons" or "tags").

          %p.description Cookies generally do not hold any information to identify an individual person, but are instead used to identify a browser on an individual machine.

          %p.description If you prefer, you can restrict, block or delete cookies by changing your browser settings but that may mean that the website won't work properly

          %p.description For more information about cookies and their impact on you and your browsing visit #{link_to 'http://www.aboutcookies.org', 'www.aboutcookies.org'}.

          %h4 TYPES OF COOKIES

          %h5 Necessary cookies

          %p.description These cookies are essential in helping you to make use of the features and services we offer on the www.octad.ch website. Without these cookies, the services you want to use cannot be provided. These cookies do not gather information about you that could be used to identify you, and they do not monitor or remember where you have been on the internet.

          %h5 Functional cookies

          %p.description These cookies allow us to provide you with a better online experience when you use our website. They do not gather or store any information which would allow us to identify you personally.

          %h5 Performance cookies

          %p.description Performance cookies help us to understand how our customers use our site, so we can keep our products and services relevant, easy to use and up to date. For example, we can see which products and services are most popular, identify when and where errors occur, and test different versions of a page in order to provide an improved online experience.

          %p.description Sometimes, the services we use to collect this information may be operated by other companies on our behalf. They may use similar technologies to cookies, known as "web beacons" or "tags". These are anonymous and, as they are only used for statistical purposes, they do not contain or collect any information that identifies you.

          %h5 Targeting cookies

          %p.description We have relationships with carefully selected and monitored suppliers (third parties) who may also set cookies during your visit. The purpose of these cookies is "behavioural advertising" (also known as "behavioural targeting" or "remarketing"), which is a means of showing you relevant products and services based on what you appear to be interested in. Although these cookies can track your visits around the web they don't know who you are. Without these cookies, online advertisements you encounter will be less relevant to you and your interests.


          %h4 MANAGING COOKIES

          %p.description Most internet browsers allow you to erase cookies from your computer hard drive, block all cookies (or just third-party cookies) or warn you before a cookie is stored on your device.

          %p.description Please note, if you choose to block all cookies, our site will not function as intended and you will not be able to use or access many of the services we provide. If you have blocked all cookies and wish to make full use of the features and services we offer, you will need to enable your cookies. You can do this in your browser (see below).

          %p.description Rather than blocking all cookies, you can choose to only block third-party cookies which will still allow our website to function as intended.

          %h5 How to manage cookies on your PC

          %p.description To enable cookies on our website, follow the steps below.

          %h5 Google Chrome

          %ol
            %li Click "Tools" at the top of your browser and select "Settings".
            %li Click "Show advanced settings", scroll down to the section "Privacy" and click "Content Settings."
            %li Select "Allow local data to be set". To only acept first-party cookies, check the box next to "Block all third-party cookies without exception"

          %h4 Microsoft Internet Explorer 6.0, 7.0, 8.0, 9.0

          %ol
            %li Click "Tools" at the top of your browser and select "Internet Options", then click the "Privacy" tab.
            %li Check that the level of your privacy is set to Medium or lower, which will allow the use of cookies in your browser.
            %li If set above medium level it will prevent the use of cookies.

          %h5 Mozilla Firefox

          %ol
            %li Click "Tools" at the top of your browser and select "Options".
            %li Then select the "Privacy" icon.
            %li Click the "Cookies" and select "Allow pages to create a cookie."

          %h5 Safari

          %ol
            %li Click the gear icon at the top of your browser and select "Settings".
            %li Click the "Privacy" tab, then select the option "Disable the use of cookies by third parties and advertising cookies."
            %li Click "Save".

          %h4 How to manage cookies on your Mac

          %p.description To enable cookies on our website, follow the steps below.

          %h5 Microsoft Internet Explorer 5.0 on OSX

          %ol
            %li Click on "Explorer" at the top of your browser and select "Settings".
            %li Scroll down to the "Cookies" section in the "Received Files".
            %li Select "Do not ask."

          %h5 Safari on OSX

          %ol
            %li Click "Safari" on the top of your browser and select "Settings".
            %li Click the "Privacy" and then "Enable cookies."
            %li Select "only the pages you have visited."

          %h4 Mozilla and Netscape on OSX

          %ol
            %li Click "Mozilla" or "Netscape" at the top of your browser and select "Settings".
            %li Scroll down to the "Cookies" under "Privacy & Security".
            %li Select "Allow cookies only to the original site."

          %h4 Opera

          %ol
            %li Click "Menu" on the top of your browser and select "Settings".
            %li Then select "Options" tab and the "Advanced".
            %li Select "Enable cookies."

app/views/home/faq.html.haml
.row
  .col-md-8.col-md-offset-2
    %h2 FAQ
    %h4 General
    #acordeon1
      #accordion1.panel-group
        - @faqs.general.group_by(&:heading).each do |heading, faqs|
          %h5=heading
          - faqs.each do |f|
            .panel.panel-border.panel-default
              %a{"data-toggle" => "collapse", :href => "#collapse-#{f.id}"}
                .panel-heading
                  %h4.panel-title
                    = f.title
                    %i.ti-angle-down
              .panel-collapse.collapse{id: "collapse-#{f.id}"}
                .panel-body
                  = f.body.html_safe
    %h4 For Students
    #acordeon
      #accordion.panel-group
        - @faqs.student.group_by(&:heading).each do |heading, faqs|
          %h5=heading
          - faqs.each do |f|
            .panel.panel-border.panel-default
              %a{"data-toggle" => "collapse", :href => "#collapse-#{f.id}"}
                .panel-heading
                  %h4.panel-title
                    = f.title
                    %i.ti-angle-down
              .panel-collapse.collapse{id: "collapse-#{f.id}"}
                .panel-body
                  = f.body.html_safe
    %h4 For Professors
    #acordeon2
      #accordion2.panel-group
        - @faqs.professor.group_by(&:heading).each do |heading, faqs|
          %h5=heading
          - faqs.each do |f|
            .panel.panel-border.panel-default
              %a{"data-toggle" => "collapse", :href => "#collapse-#{f.id}"}
                .panel-heading
                  %h4.panel-title
                    = f.title
                    %i.ti-angle-down
              .panel-collapse.collapse{id: "collapse-#{f.id}"}
                .panel-body
                  = f.body.html_safe

app/views/home/index.html.haml
.wrapper
  .landing-header
    .container
      .motto.col-lg-8
        %small MISSION
        %h3.m-t-10
          %span.light-weight At The Brasden College, we believe that
          everyone deserves access to an affordable, high-quality bachelor's degree.
        %p We bring together the best professors, researchers, and teachers from around the world to teach classes online leading to a formal degree. Members of our network have PhD's from Ivy League institutions and first-class international universities, won billions of dollars in research grants, received countless awards, and taught thousands of students.
        %p We empower professors with our smart teaching platform using video learning technology to allow them to instruct and guide students from across the globe. This technology has allowed us to build over 1,000 courses for students in over 20 countries.
        %p If you're interested in starting your degree at The Brasden College or just want to learn more about what we do, get in touch to start.
      .motto.col-lg-4.p-b-20
        .text-center
          = image_tag 'logo.svg', width: "70%", class: 'main-logo hidden-md hidden-sm hidden-xs'
          = link_to user_facebook_omniauth_authorize_path, class: 'btn btn-block btn-social btn-lg btn-fill btn-facebook' do
            %i.fa.fa-facebook
            Apply with Facebook
          %br
          = link_to 'or with email', new_user_registration_path
  .main
    .section.text-center.landing-section
      .container
        .row
          .col-md-8.col-md-offset-2
            %h2 We're a professor-driven institution
            %h5 At Brasden, all course are taught by professors who have complete control over the learning experience. Professors earn all of their students' tutition (less a platform fee), have complete autonomy over their courses, and have freedom to live and work from anywhere in the globe.
            %br/
            %h4 Interested in teaching?
            %br/
            %a.btn.btn-danger.btn-lg.btn-fill{:href => about_path } Learn More
    .section.section-light-brown.landing-section
      .container
        .row
          .col-md-4.column
            %h4 Affordable Online Degrees
            %p Earn your entire Bachelor's degree from a dozen of our liberal arts majors for the price of a single course at a traditional college.
            %a.btn.btn-danger.btn-simple{:href => about_path}
              See more
              %i.fa.fa-chevron-right
          .col-md-4.column
            %h4 Small class sizes
            %p Receive personal attention in our courses, where the average class size is 15 students and never greater than 25 in a single course.
            %a.btn.btn-danger.btn-simple{:href => about_path}
              See more
              %i.fa.fa-chevron-right
          .col-md-4.column
            %h4 Faster Time to Degree
            %p Study at your own pace, or at an accellerated page, to earn you bachelors degree in a little as 80 weeks, from anywhere in the world.
            %a.btn.btn-danger.btn-simple{:href => about_path}
              See more
              %i.fa.fa-chevron-right

app/views/home/robots.text.haml
Sitemap:
= sitemap_url

app/views/home/thanks.html.haml
.wrapper
  .main
    .section.thanks-section
      .container
        .row
          .col-md-8.col-md-offset-2.text-center
            %h2.title Thanks for applying
            %p
              We review applications on a daily basis and process within 1-2 weeks.
              We evaluate based on program needs as well as applicant background.
              You will receive an email from us about the status of your application soon.
        .row
          .col-md-6.col-md-offset-3.m-t-50
            %button.btn.btn-primary.btn-fill.btn-block Read our FAQs
- if Rails.env.production?
  :javascript
    fbq('track', 'CompleteRegistration');
    var google_conversion_id = 863205962;
    var google_conversion_language = "en";
    var google_conversion_format = "3";
    var google_conversion_color = "ffffff";
    var google_conversion_label = "S0rNCPWOqm0QyvTNmwM";
    var google_remarketing_only = false;
    fbq('track', 'CompleteRegistration');
  %script{:src => "//www.googleadservices.com/pagead/conversion.js", :type => "text/javascript"}
  %noscript
    %div{:style => "display:inline;"}
      %img{:alt => "", :height => "1", :src => "//www.googleadservices.com/pagead/conversion/863205962/?label=S0rNCPWOqm0QyvTNmwM&guid=ON&script=0", :style => "border-style:none;", :width => "1"}/
  %script{:src => "//platform.twitter.com/oct.js", :type => "text/javascript"}
  :javascript
    twttr.conversion.trackPid('nwbeo', { tw_sale_amount: 0, tw_order_quantity: 0 });
  %noscript
    %img{:alt => "", :height => "1", :src => "https://analytics.twitter.com/i/adsct?txn_id=nwbeo&p_id=Twitter&tw_sale_amount=0&tw_order_quantity=0", :style => "display:none;", :width => "1"}/
    %img{:alt => "", :height => "1", :src => "//t.co/i/adsct?txn_id=nwbeo&p_id=Twitter&tw_sale_amount=0&tw_order_quantity=0", :style => "display:none;", :width => "1"}/

app/views/home/tuition.html.haml
.container
  .row.m-t-100.m-b-50
    .col-md-6.col-md-offset-3
      .info
        .description
          %h2.light-weight Tuition
          %br
          %p Our unique platform-optimized learning model means higher quality, lower costs, and a better experience.
.section.section-nude-gray
  .container
    .row.m-t-50.m-b-50
      .col-md-6.text-right
        %h1.price
          %sup.per €
          175
      .col-md-6
        %h4.light-weight.m-t-65 PER COURSE
        %p
          %b Enroll up to 4 courses as a time.
        %p
          %b Courses last 10 weeks.
        %p
          %b Course includes 3 hours of class time per week.
        %p
          While you can enroll in as many courses as you wish, only 32 courses are required to achieve a Bachelor of Arts or Bachelor of Science degree (€5,600).
        %p
          Enrolled in 4 courses at a time, a student can complete their Bachelors Degree in as little as 80 weeks (1 year, 7 months).
.section.section-light-brown
  .container
    .row
      .col-md-12.text-center
        %h4 Interested in earning your degree?
        %br/
        %a.btn.btn-danger.btn-lg.btn-fill{:href => new_user_registration_path } Apply Now
.container
  .row.m-t-100.p-b-20
    .col-md-12
      %small FAQS
    .col-md-6.m-t-20
      %p.p-b-10
        %b DO YOU OFFER FINANCIAL AID?
        %br
        %small No. We believe our pricing is affordable for all students wishing to pursue a Bachelors Degree.
      %p
        %b DO YOU PARTICIPATE IN ANY GOVERNMENT LOAN PROGRAMS?
        %br
        %small No. We believe that our pricing should enable students to pursue higher education without participating in any higher education loan scheme.
    .col-md-6.m-t-20
      %p.p-b-10
        %b ARE YOU ACCREDITED?
        %br
        %small We believe the the quality of an education lies in the teaching not a third-party assessment, and that accreditation prohibits innovation within the online higher education experience, so have chosen not to pursue accreditation.
      %p
        %b WHERE ARE YOU LOCATED?
        %br
        %small Our network of students and teachers are in countries and cities around the world; however, our corporate headquarters is based out of Brasden, Switzerland.