config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'errors/not_found'
  get 'errors/internal_server_error'
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions', omniauth_callbacks: 'users/omniauth_callbacks' }

  HomeController.action_methods.each do |action|
    get action.to_sym, to: "home##{action}"
  end
  resources :articles, only: [:show]

  resources :divisions, only: [:index] do
    resources :degrees, only: [:show]
  end

  resources :contacts, only: %i[new create]
  resources :setup, only: %i[show update]
  resources :cards, only: [:new, :create, :destroy]
  resources :reservations, only: %i[index destroy]
  resources :charges, only: [:index]
  resources :transfers, only: [:index]
  resources :availabilities, only: %i[index show destroy update]
  resources :enrollments, only: %i[index update] do
    resources :evaluations, only: %i[new create]
  end
  resources :courses, except: [:edit, :update]
  resources :slots, only: [:index]
  resources :emails, only: [:create]
  resources :users, only: %i[show update] do
    resources :appointments, only: [:new, :create, :destroy]
    member do
      get :finish_signup
      patch :complete_signup
      get :student_welcome
      get :professor_welcome
      get :interview
      get :reject
      get :approve
    end
  end

  resources :petitions, only: %i[create show]
  resources :instances, only: [:show, :update] do
    member { get :confirmed }
    resources :posts, only: [:create]
    resources :meetings, only: %i[show edit update]
    resources :assignments, except: [:index] do
      resources :submissions, only: %i[new create update]
    end
  end
  resources :dashboard, only: [:index] do
    collection { get :activities }
  end

  resources :conversations, only: [:index, :show] do
    member do
      post :reply
    end
  end

  resources :messages, only: %i[new create]
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  authenticated :user do
    root 'dashboard#index', as: :authenticated_root
  end

  root to: 'home#index'
  mount StripeEvent::Engine, at: '/stripe-events'
  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
  get 'sitemap.xml' => 'home#sitemap', format: :xml
  get 'robots.txt' => 'home#robots', format: :text
end

app/models/enrollment.rb
# frozen_string_literal: true

class Enrollment < ApplicationRecord
  belongs_to :user
  belongs_to :charge
  belongs_to :instance
  validates :user, presence: true
  enum status: %i[pending active rejected withdrawal]

  after_create :notify_student, unless: :skip_callbacks
  after_create :charge_student, unless: :skip_callbacks
  after_update :process_refunds, unless: :skip_callbacks
  after_commit :update_meeting_participants, unless: :skip_callbacks

  validates :grade, inclusion: { in: 1..100, allow_nil: true }

  after_update :notify_grade, unless: :skip_callbacks

  def notify_grade
    if grade_changed?
      Activity.create(
        subject: self,
        name: 'grade_added',
        direction: 'to',
        user: user
      )
    end
  end

  def notify_student
    Activity.create(
      subject: self,
      name: 'enrollment_added',
      direction: 'to',
      user: user
    )
  end
  handle_asynchronously :notify_student

  def charge_student
    charge = Charge.create!(
      amount: (ENV['COURSE_PRICE'].to_i * 100),
      card: user.cards.find_by(default: true),
      instance: instance
    )
    update(charge: charge)
  end
  handle_asynchronously :charge_student

  def update_meeting_participants
    instance.schedule.meetings.each(&:update_meeting_participants)
  end
  handle_asynchronously :update_meeting_participants

  def process_refunds
    if status_changed?(from: 'active', to: 'withdrawal') || status_changed?(from: 'active', to: 'rejected')
      if (instance.schedule_start_date + 7.days) > Time.current
        refund = Refund.create(amount: 20_000, charge: charge, user: user)
        UserMailer.refund_created(self, refund)
      end
      UserMailer.withdrawal_mail(self)
    end
  end
end

app/controllers/enrollments_controller.rb
# frozen_string_literal: true

class EnrollmentsController < ApplicationController
  before_action :authenticate_user!
  before_action :check_for_card
  before_action :set_enrollment, only: [:update]

  add_breadcrumb 'Dashboard', :authenticated_root_path
  load_and_authorize_resource

  def index
    add_breadcrumb 'Transcript', :enrollments_path
    @enrollments = current_user.enrollments
  end

  def update
    @enrollment.update(enrollment_params)
    respond_to do |format|
      format.json { respond_with_bip(@enrollment) }
    end
  end

  private

  def set_enrollment
    @enrollment = Enrollment.find(params[:id])
  end

  def enrollment_params
    params.require(:enrollment).permit(:grade)
  end
end

app/views/enrollments/_enrollment.html.haml
%tr
  %td.text-center= link_to enrollment.instance.course.id, enrollment.instance, class: 'link-info'
  %td= link_to enrollment.instance.course_name, enrollment.instance, class: 'link-info'
  %td= link_to enrollment.instance.user.name, enrollment.instance.user, class: 'link-info'
  %td= enrollment.instance.enrollments.length
  %td= enrollment.grade ? enrollment.grade : "---"
  %td= link_to 'access', enrollment.instance, class: 'btn btn-primary btn-sm'

app/views/enrollments/_enrollment_fields.html.haml
%tr.nested-fields
  %td
    = f.hidden_field :user_id, value: reservation.user_id
    = f.hidden_field :status, value: 'pending'
    = link_to reservation.user.name, reservation.user
  %td Yes
  %td.text-right= link_to_remove_association "remove", f

app/views/enrollments/_enrollments.html.haml
%h3 Active Courses
- if current_user.enrollments.any?
  .table-responsive
    %table.table
      %thead
        %tr
          %th.text-center #
          %th Name
          %th Professor
          %th Students
          %th Grade
          %th
      %tbody
        = render current_user.enrollments.order('created_at asc')
- else
  %h5 No Active courses

app/views/enrollments/index.html.haml
.container.dashboard
  .row.m-t-50
    = render 'layouts/sidebar'
    .col-md-9.col-sm-9.col-xs-12
      = render 'layouts/breadcrumbs'
      %h3 Current and past courses
      - if current_user.enrollments.any?
        .card.p-20
          .table-responsive
            %table.table
              %thead
                %tr
                  %th.text-center #
                  %th Name
                  %th Professor
                  %th Classmates
                  %th Grade
              %tbody
                = render @enrollments.order('created_at asc')
      - else
        %h5 No Active courses
      %h3 Graduation Petitions
      - if current_user.petitions.any?
        .card.p-20
          .table-responsive
            %table.table
              %thead
                %tr
                  %th #
                  %th Degree
                  %th Status
              %tbody
                = render current_user.petitions.order('created_at asc')
      - else
        = link_to 'Create Petition', petitions_path, method: :post, class: 'btn btn-primary btn-fill'