config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'errors/not_found'
  get 'errors/internal_server_error'
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions', omniauth_callbacks: 'users/omniauth_callbacks' }

  HomeController.action_methods.each do |action|
    get action.to_sym, to: "home##{action}"
  end
  resources :articles, only: [:show]

  resources :divisions, only: [:index] do
    resources :degrees, only: [:show]
  end

  resources :contacts, only: %i[new create]
  resources :setup, only: %i[show update]
  resources :cards, only: [:new, :create, :destroy]
  resources :reservations, only: %i[index destroy]
  resources :charges, only: [:index]
  resources :transfers, only: [:index]
  resources :availabilities, only: %i[index show destroy update]
  resources :enrollments, only: %i[index update] do
    resources :evaluations, only: %i[new create]
  end
  resources :courses, except: [:edit, :update]
  resources :slots, only: [:index]
  resources :emails, only: [:create]
  resources :users, only: %i[show update] do
    resources :appointments, only: [:new, :create, :destroy]
    member do
      get :finish_signup
      patch :complete_signup
      get :student_welcome
      get :professor_welcome
      get :interview
      get :reject
      get :approve
    end
  end

  resources :petitions, only: %i[create show]
  resources :instances, only: [:show, :update] do
    member { get :confirmed }
    resources :posts, only: [:create]
    resources :meetings, only: %i[show edit update]
    resources :assignments, except: [:index] do
      resources :submissions, only: %i[new create update]
    end
  end
  resources :dashboard, only: [:index] do
    collection { get :activities }
  end

  resources :conversations, only: [:index, :show] do
    member do
      post :reply
    end
  end

  resources :messages, only: %i[new create]
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  authenticated :user do
    root 'dashboard#index', as: :authenticated_root
  end

  root to: 'home#index'
  mount StripeEvent::Engine, at: '/stripe-events'
  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
  get 'sitemap.xml' => 'home#sitemap', format: :xml
  get 'robots.txt' => 'home#robots', format: :text
end

app/models/card.rb
# frozen_string_literal: true

class Card < ApplicationRecord
  extend FriendlyId
  attr_accessor :token, :number, :expiration, :cvc, :currency
  belongs_to :user
  has_many :transfers, dependent: :destroy
  has_many :charges, dependent: :destroy
  validates :user, :card_type, :last_four, :expiration_month, :expiration_year, presence: true
  enum card_type: %i[credit debit]
  enum status: %i[active removed]
  enum brand: %i[visa mastercard amex jcb discover diners]

  before_create :process_stripe, on: [:create], unless: :skip_callbacks
  after_create :set_default, unless: :skip_callbacks
  after_destroy :set_default_destroyed, unless: :skip_callbacks

  before_create :set_default_card
  friendly_id :code, use: :slugged


  def code
    Digest::SHA1.hexdigest id.to_s
  end

  def set_default_card
    self.default ||= true
  end

  def process_stripe
    if user
      case card_type
      when 'credit'
        customer = Stripe::Customer.retrieve(user.stripe_customer_token)
        card_token = customer.sources.create(source: token)
        self.stripe_card_token = card_token.try(:id)
      when 'debit'
        account = Stripe::Account.retrieve(user.stripe_account_token)
        card_token = account.external_accounts.create(external_account: token)
        self.stripe_card_token = card_token.try(:id)
      end
    end
  end

  def set_default
    update(default: true) if user.cards.active.count == 1
  end

  def set_default_destroyed
    user.cards.first.update(default: true) if user.cards.count == 1
  end
end

app/controllers/cards_controller.rb
# frozen_string_literal: true

class CardsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_card, only: :destroy
  add_breadcrumb 'Dashboard', :authenticated_root_path
  load_and_authorize_resource

  def new
    add_breadcrumb 'New Card', new_card_path
    @card ||= current_user.cards.build
  end

  def create
    @card = current_user.cards.build(card_params)
    if @card.save
      redirect_to edit_user_registration_path
    else
      render :new
    end
  end

  def destroy
    @card.update(status: 'removed', default: false)
    redirect_to edit_user_registration_path
  end

  private

  def set_card
    @card = current_user.cards.find(params[:id])
  end

  def card_params
    params.require(:card).permit(:name, :token, :card_type, :currency, :number,
      :expiration, :expiration_month, :last_four, :expiration_year, :cvc
    )
  end
end

app/views/cards/_card.html.haml
%tr
  %td= card.last_four
  %td= "#{card.expiration_month}/#{card.expiration_year}"
  %td= card.default ? "Default" : ""
  - unless resource.cards.count == 1
    %td= link_to 'Delete', card_path(card), method: :delete, data: { confirm: "Are you sure?" }

app/views/cards/new.html.haml
.container.dashboard
  .row.m-t-50
    = render 'layouts/sidebar'
    .col-md-9.col-sm-9.col-xs-12
      = render 'layouts/breadcrumbs'
      = simple_form_for @card, validate: true, html: { id: 'new_card' } do |f|
        %h4 Add a new card
        .card
          .content
            .row
              .col-md-12
                = render 'shared/error_messages', object: f.object
                .payment-errors
                .row
                  .col-md-6
                    %label Name on card
                    = f.text_field :name, class: 'form-control border-input', "data-stripe" => "name"
                  .col-md-6
                    .row.m-t-30
                      .col-md-2
                        = image_tag 'cards/credit-cards_visa.png'
                      .col-md-2
                        = image_tag 'cards/credit-cards_mastercard.png'
                      .col-md-2
                        = image_tag 'cards/credit-cards_maestro.png'
                      .col-md-2
                        = image_tag 'cards/credit-cards_default.png'
                .row.m-t-10.m-b-50
                  -# %button#apple-pay-button
                  .col-md-6.col-xs-6
                    %label Card number
                    = f.hidden_field :card_type, value: current_user.professor? ? 'debit' : 'credit'
                    = f.hidden_field :currency, value: 'usd', "data-stripe" => "currency"
                    = f.text_field :last_four, class: 'hidden'
                    = f.text_field :token, class: 'hidden'
                    = f.text_field :number, class: 'form-control credit-card-number card-attributes border-input', "data-stripe" => "number"
                  .col-md-3.col-xs-3
                    %label Expires
                    = f.text_field :expiration, "data-stripe" => 'exp', class: 'form-control credit-card-expiration card-attributes border-input', placeholder: 'MM / YY'
                    = f.text_field :expiration_month, class: 'card-attributes hidden'
                    = f.text_field :expiration_year, class: ' card-attributes hidden'
                  .col-md-3.col-xs-3
                    %label CSV
                    %a.form-control-hint.glyphicon.glyphicon-info-sign{"data-placement" => "top", "data-toggle" => "tooltip", :href => "#", :title => "CSV code from card back side"}
                    = f.text_field :cvc, class: 'form-control credit-card-cvc card-attributes border-input', "data-stripe" => "cvc"
        .row
          .col-xs-12.m-b-50
            = f.submit :complete, class: 'btn btn-primary btn-fill btn-block'